### ISSUE TITLE
About "3.1 DL Libraries Prebuilt Binaries"

### ISSUE THREAD

**Issue by ddf1826120803** [UbiquitousLearning/MobileDLFrameworksBenchmark#1]
Hi, 
I am very intersting in  "3.1 DL Libraries Prebuilt Binaries".  It seems that in this way, APK is not required to run the model. However, I don't know how to custom DL libraries for testing models in android. Can you give me some tips? 

Any steps, documentation, and example projects would be very beneficial to me..

Thank you for any support!

**Comment by lx200916** [comment]
Hi dff,
Yes, it's unnecessary to generate & install a full application if you just want to do some model tests on the device. Most DL Libs support the C interface so you can build a simple command-line binary thus you can run it via `ADB shell` on the Android device. Some Libs offer the benchmark binary already, and you can also modify the source if necessary.

* TFLite: See [Official Doc Here](https://www.tensorflow.org/lite/performance/measurement). TF provides pre-built binaries and example shell codes.
* NCNN: See [Benchmark](https://github.com/Tencent/ncnn/tree/master/benchmark). However, the models to be loaded are hard-coded. You may modify `benchncnn.cpp` and add your custom models.
*  MNN: See [Official Doc Here](https://www.yuque.com/mnn/en/tool_benchmark). 
* Pytorch Mobile: See [Official Doc](https://pytorch.org/tutorials/recipes/mobile_perf.html). 
* SNPE: See [Official Doc](https://developer.qualcomm.com/sites/default/files/docs/snpe/benchmarking.html). SNPE provides a Py command-line tool that runs on your HOST machine instead of your Android device. The tool helps you push the benchmark binary and model files to the device and run the benchmark test. 
* MACE: See [Doc](https://mace.readthedocs.io/en/latest/user_guide/benchmark.html). They also provide some host tools and the whole workflow is taken over by Bazel/CMake. You may need to write the YAML configs and try to convert your models to MACE, then run the whole benchmark. (It's a quite tough way, I'd say....)

Some links and tips are listed above. Most Libs are open-source so you can modify the source files and rebuild them if needed. 
Hope my words helpful.

**Comment by ddf1826120803** [comment]
@lx200916 Thx a lot!
